### ISSUE TITLE
Snap does not work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by tpeulen** [Fluorescence-Tools/chisurf#34]
On Noahs Laptop chisurf does not start when using the snap distribution. There is an error (likely missing libary) with the snap package.

See error message below

'''
Traceback (most recent call last):
  File "mfm_gui.py", line 27, in <module>
    import mfm
  File "/snap/chisurf/7/mfm/__init__.py", line 226, in <module>
    from . import fitting
  File "/snap/chisurf/7/mfm/fitting/__init__.py", line 3, in <module>
    import models
  File "/snap/chisurf/7/mfm/fitting/models/__init__.py", line 16, in <module>
    from mfm import plots
  File "/snap/chisurf/7/mfm/plots/__init__.py", line 4, in <module>
    from .MolView import *
  File "/snap/chisurf/7/mfm/plots/MolView.py", line 6, in <module>
    from OpenGL.GL import *
  File "/snap/chisurf/7/python/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/snap/chisurf/7/python/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/snap/chisurf/7/python/lib/python2.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/snap/chisurf/7/python/lib/python2.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
'''

**Comment by tpeulen** [comment]
No snaps planed -> use AppImage insted
